### ISSUE TITLE
Typo Error in Exercise 1.36

### ISSUE THREAD

**Issue by albondad** [sgignoux/codology.net#2]
I think this is just a minor typo issue, but I noticed you were using (log 100) instead of (log 1000) as stated in the problem which is changing the results.

Link:
https://github.com/albondad/codology.net/blob/master/content/post/SICP-Solution-Exercise-1-36.md

**Comment by sgignoux** [comment]
@albondad Thanks a lot for pointing this out. I fixed it.

I should have checked that the `(expt 4.555537551999825 4.555537551999825)` ≈ 1000

**Comment by albondad** [comment]
Haha no problem.
